fixtures:
  symlinks:
    cloudwatch: '#{source_dir}/site/cloudwatch'
    common: '#{source_dir}/site/common'
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.15.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.5"
    epel:
      repo: "stahnma/epel"
      ref: "1.2.2"
    sudo:
      repo: "saz/sudo"
      ref: "3.1.0"
