fixtures:
  symlinks:
    cloudwatch: '#{source_dir}'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    awscli: "jdowning/awscli"
    aws:    "puppetlabs-aws"
    epel:   "stahnma/epel"
  repositories:
    python:
      repo:   "git://github.com/mpdude/puppet-python"
      branch: "rename-pip-package"
