fixtures:
  symlinks:
    cloudwatch: '#{source_dir}'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    awscli: "jdowning/awscli"
    aws: "puppetlabs-aws"
    epel: "stahnma/epel"
