---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: test/integration
  ignore_spec_fixtures: true
  custom_facts:
    aws_api_key: <%= ENV['AWS_ACCESS_KEY_ID']%>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>

transport:
  name: sftp

platforms:
  - name: centos-7.2

suites:
  - name: default
    provisioner:
      manifest: default/init.pp
