---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: examples
  ignore_spec_fixtures: true
  custom_facts:
    aws_api_key: <%= ENV['AWS_ACCESS_KEY_ID']%>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>

transport:
  name: sftp

platforms:
  - name: centos-7.2

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance --format RspecJunitFormatter --out build/junit.xml'

suites:
  - name: default
    provisioner:
      manifest: init.pp
    verifier:
      patterns:
        - 'spec/acceptance/**_spec.rb'
