logging:
  version: 1

  loggers:
    root:
      level: INFO
      handlers: [logfile]

    CWAgent:
      level: INFO
      handlers: [logfile]

  handlers:

    logfile:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/cloudwatch-agent/cw_agent.log
      formatter: simpleFormatter
      level: NOTSET
      maxBytes: 4194304 # 4MB max
      backupCount: 3

  formatters:

    simpleFormatter:
      class: Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'
