#HOSTS:
#  centos-7-base:
#    vmname: centos-7-base
#    platform: el-7-x86_64
#    hypervisor: ec2
#    amisize: t2.small
#    snapshot: foss
#    user: centos
HOSTS:
  centos-7-x64:
    platform: "el-7-x86_64"
    box: "centos/7"
    box_url: 'https://atlas.hashicorp.com/centos/boxes/7/versions/1603.01/providers/virtualbox.box'
    hypervisor: vagrant
    roles:
      - default
      - base
CONFIG:
  type: foss
  log_level: verbose
  masterless: true