logging:
  version: 1
  root:
    level: NOTSET
    handlers: [logfile]

  cloudwatch-agent:
    level: DEBUG
    handlers: [logfile]
    qualname: cloudwatch-agent

  handlers:

    logfile:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/cloudwatch-agent/cloudwatch-agent.log
      formatter: simpleFormatter
      level: NOTSET
      maxBytes: 4096
      backupCount: 3

    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: NOTSET

  formatters:

    simpleFormatter:
      class: Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'

metrics:

  - name   : DiskSpace
    params : '-a'

  - name   : Memory
    params : '-a'
